xixi/cheatsheet/models.py
# -*- coding: utf-8 -*-
"""Xchange models."""
from datetime import datetime as dt
from app.database import Column, Model, db, reference_col, relationship, SurrogatePK


class Order(SurrogatePK, Model):
    """A order"""

    __tablename__ = 'orders'
    stock_id = Column(db.Integer, unique=True, nullable=True)
    order_type = Column(db.String(20), nullable=True)
    quantity = Column(db.Integer, nullable=True)
    price = Column(db.Integer, nullable=True)
    create_at = Column(db.DateTime, default=dt.utcnow(), nullable=False)
    updated_at = Column(db.DateTime, default=dt.utcnow, nullable=False)
    user_id = reference_col('users', nullable=False)
    fulfilled_at = Column(db.DataTime, nullable=True)
    status = Column(db.String(20), nullable=True)

    def __init__(self, stock_id, order_type, quantity, price, **kwargs):
        """Create instance."""
        db.Model.__init__(stock_id=stock_id, order_type=order_type, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Order({stock_id})>'.format(stock_id=self.stock_id)


class Fill(SurrogatePK, Model):

    __tablename__ = 'fills'
    price = Column(db.Integer, nullable=True)
    quantity = Column(db.Integer, nullable=True)
    create_at = Column(db.DateTime, nullable=False, index=True)
    updated_at = Column(db.DateTime, nullable=False, index=True)
    buy_order_id = Column(db.Integer, nullable=True)
    sell_order_id = Column(db.Integer, nullable=True)

    def __init__(self, price, **kwargs):
        db.Model.__init__(price=price, **kwargs)


class Stock(SurrogatePK, Model):

    __tablename__ = 'stocks'
    name = Column(db.String(20), nullable=True)
    symbol = Column(db.String(20), nullable=True)
    create_at = Column(db.DateTime, nullable=False)
    updated_at = Column(db.DateTime, nullable=False)

    def __init__(self, name, **kwargs):
        db.Model.__init__(name=name, **kwargs)

xixi/cheatsheet/__init__.py
# -*- coding: utf-8 -*-
"""The cheatsheet module, include nav bar cheatsheets filed."""
from . import views  # noqa

xixi/cheatsheet/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, abort, render_template

blueprint = Blueprint('cheatsheet', __name__, url_prefix='/cheatsheet', static_folder='../static')


@blueprint.route('/')
def home():
    """Cheatsheet home."""
    return render_template('cheatsheets/home.html')


@blueprint.route('/<string:page>', methods=['GET'])
def get_cheatsheet(page):
    """Return cs page by page."""
    try:
        return render_template('cheatsheets/{0}.html'.format(page))
    except Exception:
        abort(404)

xixi/templates/cheatsheets/cpp-basic-cs.html
{% extends "layout.html" %}

{% block jumbotron %}
<div class="jumbotron">
   <h1>C++ Cheat Sheet</h1>
   <p>Cheat sheet of C++. Some basic concept for a C++ programmer need to know.</p>
</div>
{% endblock %}

{% block body %}
<div class="row col-md-4 col-xs-12">

<h3>Basic Usage of Reference and Pointer</h3>
<pre class="code c++">
#include &lt;iostream&gt;
using namespace std;

int main(int argc, char* argv[])
{
   int a = 5566;
   int *p_a_addr = &a;
   int &r_a_addr = a;

   /* value of a*/
   cout &lt;&lt; a &lt;&lt; endl;
   /* address of a */
   cout &lt;&lt; &a &lt;&lt;endl;
   /* address of a */
   cout &lt;&lt; p_a_addr &lt;&lt; endl;
   /* address of pointer */
   cout &lt;&lt; &p_a_addr &lt;&lt;endl;
   /* value of a */
   cout &lt;&lt; r_a_addr &lt;&lt; endl;
   /* address of a */
   cout &lt;&lt; &r_a_addr &lt;&lt; endl;
   return 0;
}

/* 
output:

5566
0x7fff586ef6ec
0x7fff586ef6ec
0x7fff586ef6e0
5566
0x7fff586ef6ec
*/
</pre>


<h3>Lambda Function</h3>
<pre class="code c++">
/* Lambda since C++11 */
#include &lt;iostream&gt;
using namespace std;

int main(int argc, char *argv[])
{
   int a = 8;
   int sa = 0;

   /* lambda square(since c++11) */
   sa = [](int x) {return x*x;}(a);
   cout &lt;&lt; "a = " &lt;&lt; a &lt;&lt; endl;
   cout &lt;&lt; "square a = "
        &lt;&lt; sa &lt;&lt; endl;
   
   return 0;
}
/*
bash&gt; g++ ex.cpp --std=c++11
output:

a = 8
square a = 64
*/
</pre>

<h3>Template in C++</h3>
<pre class="code c++">
#include &lt;iostream&gt;
using namespace std;

template &lt;class T&gt; struct Cls {
   T var;
   Cls(T in):var(in) {
      var = in; 
   };
   void spam() {
      cout &lt;&lt; var &lt;&lt; endl;
   };
};

int main(int argc, char *argv[])
{
   Cls&lt;int&gt; obj1(5566);
   Cls&lt;double&gt; obj2(95.27);
   
   obj1.spam();
   obj2.spam();

   return 0;
}
/* 
output:

5566
95.27
*/
</pre>

<h3>Class "operator" Overloading</h3>
<pre class="code c++">
#include &lt;iostream&gt;
using namespace std;

class cls {
public:
   /* obj++ operation */
   cls operator++(int) {
      cls tmp(idx);
      idx++;
      return tmp; 
   };
   /* ++obj operation */
   cls& operator++() {
      ++idx;
      return *this;
   };
   void spam() {
      cout &lt;&lt; "idx val = "
           &lt;&lt; idx &lt;&lt; endl;
   };
   cls(int x) :idx(x) {};
private:
   int idx;
};

int main(int argc, char *argv[])
{
   cls obj(5566);

   obj.spam();
   ++obj;
   obj.spam();
   obj++;
   obj.spam();
   return 0;
}
/*
output:

idx val = 5566
idx val = 5567
idx val = 5568
*/
</pre>

</div> <!-- ./row1 -->

<div class="row col-md-4 col-xs-12">

<h3>Different between Pointer and Reference</h3>
<pre class="code c++">
#include &lt;iostream&gt;
using namespace std;

int main(int argc, char *argv[])
{
   int a = 5566;
   int b = 9527;
   int *ptr1, *ptr2;
   int &ref1 = a; 
   int &ref2 = b;

   ptr1 = &a;
   ptr2 = &b;
   cout &lt;&lt; "b value will not change" 
        &lt;&lt; endl;
   cout &lt;&lt; "val b = "
        &lt;&lt; b  &lt;&lt; endl;
   ptr2 = &a;
   cout  &lt;&lt; "val b = "
         &lt;&lt; b  &lt;&lt; endl;

   cout  &lt;&lt; "b value will change"
         &lt;&lt; endl;
   cout  &lt;&lt; "val b = "
         &lt;&lt; b  &lt;&lt; endl;
   ref2 = a;
   cout  &lt;&lt; "val b = "
         &lt;&lt; b  &lt;&lt; endl;
   
   return 0;
}

/* 
output:

b value will not change
val b = 9527
val b = 9527
b value will change
val b = 9527
val b = 5566
*/
</pre>

<h3>C++ struct</h3>
<pre class="code c++">
/* C++ struct is same as class
 * which all members are public.
 */
#include &lt;iostream&gt;
using namespace std;

struct cppstruct {
   int a;
   double b;
   void spam(){
     cout &lt;&lt; a &lt;&lt; endl; 
     cout &lt;&lt; b &lt;&lt; endl;
   };
};

class cls {
public:
   int a;
   int b;
   void spam(){
      cout &lt;&lt; a &lt;&lt; endl;
      cout &lt;&lt; b &lt;&lt; endl;
   };
};

int main(int argc, char *argv[])
{
   cppstruct obj1;
   cls obj2;

   cout &lt;&lt; "cpp strcut" 
        &lt;&lt; endl;
   obj1.a = 5566;
   obj1.b = 9527;
   obj1.spam();

   cout &lt;&lt; "all member public class"
        &lt;&lt; endl;
   obj2.a = 1234;
   obj2.b = 5677;
   obj2.spam();
   
   return 0;
}

/*
output:

cpp strcut
5566
9527
all member public class
1234
5677
*/
</pre>

</div><!-- ./row2 -->

<div class="row col-md-4 col-xs-12">

<h3>Call by "Reference"</h3>
<pre class="code c++">
#include &lt;iostream&gt;
using namespace std;

void spam_ptr(int *ptr)
{
   cout &lt;&lt; "addr = " 
        &lt;&lt; ptr &lt;&lt; endl; 
   cout &lt;&lt; "val = "
        &lt;&lt; *ptr &lt;&lt; endl;
}

void spam_ref(int &ref)
{
   cout &lt;&lt; "addr = "
        &lt;&lt; &ref &lt;&lt; endl;
   cout &lt;&lt; "val = "
        &lt;&lt; ref &lt;&lt;endl;
}

int main(int argc, char *argv[])
{
   int var = 5566;
   spam_ptr(&var);
   spam_ref(var);
   
   return 0;
}
/*
output:

addr = 0x7fff53c6c74c
val = 5566
addr = 0x7fff53c6c74c
val = 5566
*/
</pre>

<h3>Object Constructor</h3>
<pre class="code c++">
#include <iostream>
using namespace std;

class cls1 {
public:
   int x;
   int y;
   /* Basic Constructor */
   cls1(int a, int b) {
      cout &lt;&lt; "Construct cls1" 
           &lt;&lt; endl;
      x=a;
      y=b;
   };
   ~cls1() {
      cout &lt;&lt; "Destruct cls1" 
           &lt;&lt; endl;
   };
};

class cls2 {
public:
   int x;
   int y;
   /* Initialization Lists */
   cls2(int a, int b):x(a), y(b) {
      cout &lt;&lt; "Construct cls2"
           &lt;&lt; endl;
   }
   ~cls2() {
      cout &lt;&lt; "Destruct cls2" 
           &lt;&lt; endl;
   };
};

int main(int argc, char *argv[])
{
   cls1 obj1(5566, 9527);
   cls2 obj2(123,456);
   cout &lt;&lt; obj1.x &lt;&lt; ", "
        &lt;&lt; obj1.y &lt;&lt; endl;
   cout &lt;&lt; obj2.x &lt;&lt; ", "
        &lt;&lt; obj2.y &lt;&lt; endl;
   return 0;
}
/* 
output:

Construct cls1
Construct cls2
5566, 9527
123, 456
Destruct cls2
Destruct cls1
*/
</pre>

</div><!-- ./row3 -->

{% endblock %}

{% block script %}
{{ super() }}

{% endblock %}

xixi/templates/cheatsheets/git-cs.html
<!DOCTYPE html>
<html>
   <head>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="highlight/styles/github.css">
      <link rel="stylesheet" href="css/style.css">
      <script src="highlight/highlight.pack.js"></script>
      <script>
         $(document).ready(function(){
            $('pre.code').each(function(i, block) {
               hljs.highlightBlock(block);
            }); 
         });
      </script> 
   </head>
   <body>
      <div class="container" style="width:80%">
      <div class="jumbotron" style="background:white;">
      <h1>Git Cheat Sheet</h1>      
      <p>Cheat sheet of BASIC Git command</p>
      </div>
      <div class="row">
         <div class="col-sm-4">
<h3>Basic Command of Git</h3>
<pre class="code bash">
# init a git repo
$ git init

# clone a git repo
$ git clone [url]

# clone a git repo to spec folder
$ git clone [url] [folder]

# add file into stage
$ git add [file]
$ git add *.c  # add *.c files
$ git add .    # add add all files 

# cancel stage file
$ git reset HEAD [file]

# track current state
$ git status

# commit stage files
$ git commit 
$ git commit -m "commit msg"

# add all files and commit
# equal to:
# $ git add .
# $ git commit -m "commit msg"
$ git commit -am "commit msg"

# modify previous commit
$ git commit --amend

# diff between stage and modify file
$ git diff

# diff betweent stage and pre commit
$ git diff --staged
# or 
$ git diff --cached
</pre>

<h3>Viewing the Commit History</h3>

<pre class="code bash">
# show commit log
$ git log

# show diff between each commit
$ git log -p

# show a list of modified file
$ git log --stat

# no merge log
$ git log --no-merges

# show branch and merge history
$ git log --graph --all
</pre>
<h3>Remove or Move File</h3>
<pre class="code bash">
# unstage a file and remove
# equal to 
# $ rm [file]
# $ git rm [file]
$ git rm -f [file]

# un stage a file
$ git --cached [file]
# or 
$ git reset [file]

# move stage file
$ git mv [src-file] [dest-file]
</pre>
         </div>
         <div class="col-sm-4">
<h3>Git Basic Branching</h3>
<pre class="code bash">
# show current local branch
$ git branch 

# show remote branch
$ git branch -r

# show remote & local branch
$ git branch -a

# create a branch
$ git branch [branch name]

# create and checkout a new branch
$ git checkout -b [branch name]

# delete local branch
$ git branch -d [branch name]

# delete remote branch 
$ git branch -r -d [branch name]

# checkout branch
$ git checkout [branch name]
</pre>
<h3>Remote Branches</h3>
<pre class="code bash">
# add remote git server
$ git remote add [remote name]/[url]

# delete remote git server
$ git remote remove [remote name]

# push current commit 
$ git push [branch] [remote name]

# fetch remote repo and merge 
$ git pull

# fetch remote repo, rebase and merge
$ git pull --rebase
#or
$ git pull -r

# fetch remote repo(ex: origin)
$ git fetch origin

# create a local branch to track remote branch 
$ git checkout --track origin/[branch]

# set exist local branch to track remote branch (--set-upstream-to or -u)
$ git branch -u [lbranch] [rbranch]

</pre>
<h3>Add Alias</h3>
<pre class="code bash">
# edit ~/.gitconfig
[alias]
   co = checkout
   br = branch
   cl = clone 
   ci = commit
   la = log --graph --all
</pre>
<h3>Edit ./gitignore</h3>
<pre class="code bash">
*.o
*.py
[folder]/*.a
[folder]/*
</pre>
         </div>
         <div class="col-sm-4">
<h3>Local Merge Strategy</h3>
<pre class="code bash">
# step1: rebase branch
$ git rebase master 

# step2: checkout to master branch
$ git checkout master

# step3: merge
$ git merge [branch]

# step4: solve conflicts

# step5: add fix files
git add [fix files]

# step6: commit
git commit
</pre>
<h3>Remote Merge Strategy</h3>

<pre class="code bash">
# case1: merge track branch
$ git pull --rebase

# case2: merge untrack branch

# step1: git fetch
$ git fetch origin 

# step2: track remote branch
$ git --track origin/[branch] 

# step3: rebase
$ git rebase origin/[branch]

# step4: checkout
$ git checkout master

# step5: merge
$ git merge origin/[branch]

# step6: fix conflicts

# step7: add and commit
$ git add [files]
$ git commit 
</pre>
<h3>Undo</h3>
<pre class="code bash">
# modify previous commit
$ git commit --amend

# unstage all file
$ git reset

# unstage a file
$ git reset HEAD [file]

# cancel commit but keep all modified.
git reset HEAD^ --soft

# below are DANGEROUS commands

# unmodify a unstage file
$ git checkout -- [file]

# clean all modify and back to previous commit
$ git reset --hard
</pre>
         </div>
      </div>
      </div>
   </body>
</html>

xixi/templates/cheatsheets/gnu-autotool-cs.html
<!DOCTYPE html>

<html>
   <head>
   
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="highlight/styles/github.css">
      <link rel="stylesheet" href="css/style.css">
      <script src="highlight/highlight.pack.js"></script>
      <script>
         $(document).ready(function(){
            $('pre.code').each(function(i, block) {
               hljs.highlightBlock(block);
            }); 
         });
      </script> 
   </head>

   <body>
      <div class="container">
         <div class="jumbotron" style="background-color:white;">
            <h1>GNU Autotool Cheat Sheet</h1>
            <p>Cheat sheet of GNU Autotool. Some basic concept for a programmer need to know.</p>
         </div>
         <div class="row">
            <div class="col-sm-4">
<h3>Project structure</h3>
<pre class="code bash">
# before "bash &gt; autoreconf --install"
hello_world/
   |- Makefile.am
   |- configure.ac
   |- m4
   |- include/
   |  |- Makefile.am
   |  |- hello.h 
   |  `- world.h
   |- src/
   |  |- Makefile.am
   |  `- main.c
   `- lib/
      |- Makefile.am
      |- hello
      |  |- Makefile.am
      |  `- hello.c
      `- world
         |- Makefile.am
         `- world.c
</pre>
<h3>configure.ac</h3>
<pre class="code makefile">
# AC_INIT([PACKAGE-NAME], 
#         [VER], 
#         [BUG_REPORT_ADDR])
AC_INIT([amhello], [1.0])
AC_CONFIG_MACRO_DIR([m4])
LT_INIT
AC_PROG_CC
AC_CONFIG_HEADERS([config.h])
AC_CONFIG_FILES([
   Makefile
   include/Makefile
   lib/Makefile
   lib/hello/Makefile
   lib/world/Makefile
   src/Makefile
])
# Tell autoconf to produce "configure" script
AC_OUTPUT
</pre>
<h3>Makefile.am</h3>
<pre class="code makefile">
# Tell automake which directories need to be "make"
SUBDIRS = include lib src
ACLOCAL_AMFLAGS = -I m4
</pre>
            </div>
            <div class="col-sm-4">
<h3>lib/Makefile.am</h3>
<pre class="code makefile">
# recursively "auto make"
SUBDIRS = hello world
</pre>
<h3>lib/hello/Makefile.am</h3>
<pre class="code makefile">
# build "libtool archive"
lib_LTLIBRARIES = libhello.la

# Assign source for libhello.la
libhello_la_SOURCES = hello.c ../../include/hello.h

# Setup libhello CFLAGS
libhello_la_CFLAGS = $(AM_CFLAGS) -I../../include
</pre>

<h3>lib/hello/hello.c</h3>
<pre class="code c">
#include &lt;hello.h&gt;

void hello(void)
{
   printf("===== Hello =====\n");
}
</pre>
<h3>lib/world/Makefile.am</h3>
<pre class="code makefile">
# build "libtool archive"
lib_LTLIBRARIES = libworld.la

# Assign source for libworld.la
libworld_la_SOURCES = world.c ../../include/world.h

# Setup libworld CFLAGS
libworld_la_CFLAGS = $(AM_CFLAGS) -I../../include
</pre>

<h3>lib/world/world.c</h3>
<pre class="code c">
#include &lt;world.h&gt;

void world(void)
{
   printf("===== World =====\n");
}
</pre>
            </div>
            <div class="col-sm-4">
<h3>src/Makefile.am</h3>
<pre class="code c">
# build binary hello which will be install in bin/
bin_PROGRAMS = hello

# Specify source of binary "hello"
hello_SOURCES = main.c

# CFLAGS for binary
AM_CFLAGS = -I$(srcdir)/../include -g -Wall

# LDFLAGS for binary
hello_LDADD = ../lib/hello/libhello.la ../lib/world/libworld.la
</pre>

<h3>src/main.c</h3>
<pre class="code c">
#include &lt;hello.h&gt;

int main(int argc, char *argv[])
{
   hello();
   world();
   printf("Hello World\n");
   return 0;
}
</pre>
<h3>include/Makefile.am</h3>
<pre class="code makefile">
# Specify install header into include/
include_HEADERS = hello.h world.h
</pre>
<h3>include/hello.h</h3>
<pre class="code c">
#include &lt;stdio.h&gt;
extern void hello(void);
</pre>
<h3>include/world.h</h3>
<pre class="code c">
#include &lt;stdio.h&gt;
extern void world(void);
</pre>
<h3>Generate "configure" script</h3>
<pre class="code bash">
bash&gt; autoreconf --install
bash&gt; ./configure 
bash&gt; make && make install
</pre>

            </div>
         </div>
      </div>
   </body>

</html>

xixi/templates/cheatsheets/home.html
{% extends "layout.html"%}
{% block content %}
{{ super() }}
<section id="likes">
<div class="col-md-8 col-md-offset-2 col-xs-12">
   <div class="panel panel-default">
<!-- panel contents -->
<div class="panel-heading"><b>目录</b></div>

<!-- Table -->
<div class="table-responsive">
<table class="table table-hover">
   <thead>
      <tr><th>Subject</th><th>Description</th><th>Create time</th><th>Modify time</th></tr>
   </thead>
   <tbody>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-cs') }}">Python Basic</a>
         </td>
         <td>Python 基础</td>
         <td>2015/1/21</td>
         <td>2015/1/22</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-iter-cs') }}">Python Iterator</a>
         </td>
         <td>Python 控制结构</td>
         <td>2015/1/23</td>
         <td>2015/1/23</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-gen-cs') }}">Python Generator</a>
         </td>
         <td>Python 生成器</td>
         <td>2015/1/30</td>
         <td>2015/1/30</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-metaprogramming') }}">Python Metaprogramming</a>
         </td>
         <td>Python 元编程</td>
         <td>2015/2/4</td>
         <td>2015/2/5</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-network-cs') }}">Python Socket</a>
         </td>
         <td>Python 网络编程</td>
         <td>2015/2/21</td>
         <td>2015/2/21</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-concurrency-cs') }}">Python Concurrency</a>
         </td>
         <td>Python 并发</td>
         <td>2015/2/26</td>
         <td>2015/2/28</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-daemon-cs') }}">Python Daemon</a>
         </td>
         <td>Python demo</td>
         <td>2015/3/2</td>
         <td>2015/3/2</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-test-cs') }}">Python Test</a>
         </td>
         <td>Python 测试</td>
         <td>2015/3/5</td>
         <td>2015/3/6</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-sqlalchemy') }}">Python Sqlalchemy</a>
         </td>
         <td>Python 数据库模块sqlalchemy</td>
         <td>2015/3/11</td>
         <td>2015/3/13</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='python-pattern-in-c') }}">Python Style in C</a>
         </td>
         <td>Python c设计模式</td>
         <td>2015/4/2</td>
         <td>2015/4/2</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='cpp-basic-cs') }}">C++ Basic</a>
         </td>
         <td>C++ 基础</td>
         <td>2015/4/11</td>
         <td>2015/4/15</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='git-cs') }}">Git Basic</a>
         </td>
         <td>GIT</td>
         <td>2015/4/16</td>
         <td>2015/4/18</td>
      </tr>
      <tr>
         <td>
            <a href="{{ url_for('cheatsheet.get_cheatsheet', page='gnu-autotool-cs') }}">GNU Autotool</a>
         </td>
         <td>GNU 自动工具</td>
         <td>2015/5/3</td>
         <td>2015/5/8</td>
      </tr>
   </tbody>
</table>
</div>
   </div> <!-- ./panel -->
</div>
</section>
{% endblock %}
{% block scripts %}
{{ super() }}
{% endblock %}


xixi/templates/cheatsheets/python-metaprogramming.html
{% extends "layout.html" %}

{% block jumbotron %}
<div class="jumbotron">
   <h1>Python Cheat Sheet</h1>
   <p>Cheat sheet of Python. Some basic concepts for a Python programmer need to know.</p>
</div>
{% endblock %}

{% block body %}
<div class="row col-md-4 col-xs-12">

<h3>Debuging via Decorator</h3>
<pre class="code python">
# Using print is ugly.
&gt;&gt;&gt; def spam1():
...   print spam1.__name__
...   print 'SPAM_1'
... 
&gt;&gt;&gt; def spam2():
...   print spam2.__name__
...   print 'SPAM_2'
... 
&gt;&gt;&gt; spam1()
spam1
SPAM_1
&gt;&gt;&gt; spam2()
spam2
SPAM_2

# Using decorator
&gt;&gt;&gt; def debug(func):
...   def wrapper(*args, **kwargs):
...     print func.__name__
...     return func(*args, **kwargs)
...   return wrapper
... 
&gt;&gt;&gt; @debug
... def spam():
...   print 'SPAM'
... 
&gt;&gt;&gt; spam()
spam
SPAM
</pre>
<h3>@wraps - Get Original Function's "Description"</h3>
<pre class="code python">
&gt;&gt;&gt; from functools import wraps
&gt;&gt;&gt; def debug(func):
...     @wraps(func)
...     def wrapper(*args, **kwargs):
...         print func.__doc__
...         print func.__name__
...         return func(*args, **kwargs)
...     return wrapper
... 
&gt;&gt;&gt; @debug
... def spam():
...     '''spam function'''
...     print "SPAM"
... 
&gt;&gt;&gt; spam()
spam function 
spam
SPAM
</pre>

<h3>Decorate "class" methods</h3>
<pre class="code python">
&gt;&gt;&gt; from functools import wraps
&gt;&gt;&gt; def debug(func):
...     @wraps(func)
...     def wrapper(*args, **kwargs):
...         print "doc:", func.__doc__
...         print "func: ", func.__name__
...         return func(*args, **kwargs)
...     return wrapper
... 
&gt;&gt;&gt; def debugmethods(cls):
...     for k,v in vars(cls).items():
...         if callable(v):
...             setattr(cls, k, debug(v))
...     return cls
...
&gt;&gt;&gt; @debugmethods
... class Spam(object):
...     def hello(self):
...         ''' I am hello '''
...         print "Hello"
...     def world(self):
...         ''' I am world '''
...         print "World"
... 
&gt;&gt;&gt; s = Spam()
&gt;&gt;&gt; s.hello()
doc:  I am hello 
func:  hello
Hello
&gt;&gt;&gt; s.world()
doc:  I am world 
func:  world
World
</pre>
</div>

<div class="row col-md-4 col-xs-12">
</div>
<div class="row col-md-4 col-xs-12">
</div>
{% endblock %}

{% block script %}
{{ super() }}

{% endblock %}