xixi/cheatsheet/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, abort, render_template

blueprint = Blueprint('cheatsheet', __name__, url_prefix='/cheatsheet', static_folder='../static')


@blueprint.route('/')
def home():
    """Cheatsheet home."""
    return render_template('cheatsheets/home.html')


@blueprint.route('/<string:page>', methods=['GET'])
def get_cheatsheet(page):
    """Return cs page by page."""
    try:
        return render_template('cheatsheets/{0}.html'.format(page))
    except Exception:
        abort(404)

xixi/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

xixi/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

xixi/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Copyright 2013 ~ 2017 by <a href="https://github.com/defbobo/">Defbobo</a>
    powered by <a href="http://flask.pocoo.org">Flask</a> and <a href="https://www.python.org">Python</a></li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:defbobo@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

xixi/templates/header.html
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1 id="homeHeading">DBA, Data, QA</h1>
      <hr>
      <p>个人前端技术实验室</p>
      <a href="#about" class="btn btn-primary btn-xl page-scroll">更多</a>
    </div>
  </div>
</header>

xixi/templates/layout.html
<!DOCTYPE html>
<html lang="ch">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="author" content="">

  <title>{% block page_title %}
    熙熙
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/landing-page.css') }}"> -->
  <!-- <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}"> -->
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  <!-- Bootstrap Core CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}">

  <!-- Custom Fonts -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/font-awesome/css/font-awesome.min.css') }}">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='vendor/magnific-popup/magnific-popup.css') }}">

  <!-- Theme CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/x_creative.min.css') }}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  {% block css %}{% endblock %}

</head>
<body id="page-top">
  {% block body %}
  {% include "nav.html" %}
  {% include "header.html" %}

  <section class="bg-primary" id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Todo!</h2>
          <hr class="light">
          <p class="text-faded">todo</p>
          <a href="#services" class="page-scroll btn btn-default btn-xl sr-button">todo!</a>
        </div>
      </div>
    </div>
  </section>

  <section id="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">At Your Service</h2>
          <hr class="primary">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-diamond text-primary sr-icons"></i>
            <h3>Sturdy Templates</h3>
            <p class="text-muted">Our templates are updated regularly so they don't break.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
            <h3>Ready to Ship</h3>
            <p class="text-muted">You can use this theme as is, or you can make changes!</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
            <h3>Up to Date</h3>
            <p class="text-muted">We update dependencies to keep things fresh.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="service-box">
            <i class="fa fa-4x fa-heart text-primary sr-icons"></i>
            <h3>Made with Love</h3>
            <p class="text-muted">You have to make your websites with love these days!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="no-padding" id="portfolio">
    <div class="container-fluid">
      <div class="row no-gutter popup-gallery">
        <div class="col-lg-4 col-sm-6">
          <a href="img/portfolio/fullsize/1.jpg" class="portfolio-box">
            <img src="img/portfolio/thumbnails/1.jpg" class="img-responsive" alt="">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  Category
                </div>
                <div class="project-name">
                  Project Name
                </div>
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a href="img/portfolio/fullsize/2.jpg" class="portfolio-box">
            <img src="img/portfolio/thumbnails/2.jpg" class="img-responsive" alt="">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  Category
                </div>
                <div class="project-name">
                  Project Name
                </div>
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a href="img/portfolio/fullsize/3.jpg" class="portfolio-box">
            <img src="img/portfolio/thumbnails/3.jpg" class="img-responsive" alt="">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  Category
                </div>
                <div class="project-name">
                  Project Name
                </div>
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a href="img/portfolio/fullsize/4.jpg" class="portfolio-box">
            <img src="img/portfolio/thumbnails/4.jpg" class="img-responsive" alt="">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  Category
                </div>
                <div class="project-name">
                  Project Name
                </div>
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a href="img/portfolio/fullsize/5.jpg" class="portfolio-box">
            <img src="img/portfolio/thumbnails/5.jpg" class="img-responsive" alt="">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  Category
                </div>
                <div class="project-name">
                  Project Name
                </div>
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a href="img/portfolio/fullsize/6.jpg" class="portfolio-box">
            <img src="img/portfolio/thumbnails/6.jpg" class="img-responsive" alt="">
            <div class="portfolio-box-caption">
              <div class="portfolio-box-caption-content">
                <div class="project-category text-faded">
                  Category
                </div>
                <div class="project-name">
                  Project Name
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </section>

  <aside class="bg-dark">
    <div class="container text-center">
      <div class="call-to-action">
        <h2>Free Download at Start Bootstrap!</h2>
        <a href="http://startbootstrap.com/template-overviews/creative/" class="btn btn-default btn-xl sr-button">Download Now!</a>
      </div>
    </div>
  </aside>

  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 text-center">
          <h2 class="section-heading">Let's Get In Touch!</h2>
          <hr class="primary">
          <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
        </div>
        <div class="col-lg-4 col-lg-offset-2 text-center">
          <i class="fa fa-phone fa-3x sr-contact"></i>
          <p>123-456-6789</p>
        </div>
        <div class="col-lg-4 text-center">
          <i class="fa fa-envelope-o fa-3x sr-contact"></i>
          <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
        </div>
      </div>
    </div>
  </section>

  <!-- jQuery -->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>

  <!-- Plugin JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
  <script src="{{ url_for('static', filename='vendor/scrollreveal/scrollreveal.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/magnific-popup/jquery.magnific-popup.min.js') }}"></script>

  <!-- Theme JavaScript -->
  <script src="{{ url_for('static', filename='js/x_creative.min.js') }}"></script>



<!-- JavaScript at the bottom for fast page loading -->
<!-- {% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %} -->
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

xixi/templates/nav.html
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
    <a class="navbar-brand page-scroll" href="#page-top"> 熙熙 </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a class="page-scroll" href="#about">About</a>
        </li>
        <li>
            <a class="page-scroll" href="#services">Services</a>
        </li>
        <li>
            <a class="page-scroll" href="#portfolio">Portfolio</a>
        </li>
        <li>
            <a class="page-scroll" href="#contact">Contact</a>
        </li>
        <li><a href="{{ url_for('cheatsheet.home') }}">Cheatsheet</a></li>
      </ul>
      <!-- {% if current_user and current_user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
          <li>
              <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
          </li>
          <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

      </ul>
      {% elif form %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ url_for('public.register') }}">Create account</a></li>
      </ul>
      <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="form-group">
          {{ form.username(placeholder="Username", class_="form-control") }}
          {{ form.password(placeholder="Password", class_="form-control") }}
        </div>
        <button type="submit" class="btn btn-default">Log in</button>
      </form>
      {% endif %} -->
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>